// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_E1YDN1c7JJ2UbZ_7zyv-raaEM5raQdc',
    appId: '1:478157069158:web:62c5162b7c0e4cddbd06a7',
    messagingSenderId: '478157069158',
    projectId: 'micropong-ddbc2',
    authDomain: 'micropong-ddbc2.firebaseapp.com',
    storageBucket: 'micropong-ddbc2.firebasestorage.app',
    measurementId: 'G-PF940VWMFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqjxAQJK4SOACnhAwpWYlN2VXLXPHIS20',
    appId: '1:478157069158:android:616ba985eb0ce533bd06a7',
    messagingSenderId: '478157069158',
    projectId: 'micropong-ddbc2',
    storageBucket: 'micropong-ddbc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaUzWWo9ViPikUOFSlmeQ6U-B0VHR2T5s',
    appId: '1:478157069158:ios:828edc57b9d38c49bd06a7',
    messagingSenderId: '478157069158',
    projectId: 'micropong-ddbc2',
    storageBucket: 'micropong-ddbc2.firebasestorage.app',
    iosBundleId: 'com.example.aplikasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaUzWWo9ViPikUOFSlmeQ6U-B0VHR2T5s',
    appId: '1:478157069158:ios:828edc57b9d38c49bd06a7',
    messagingSenderId: '478157069158',
    projectId: 'micropong-ddbc2',
    storageBucket: 'micropong-ddbc2.firebasestorage.app',
    iosBundleId: 'com.example.aplikasi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_E1YDN1c7JJ2UbZ_7zyv-raaEM5raQdc',
    appId: '1:478157069158:web:3a69c6603452c659bd06a7',
    messagingSenderId: '478157069158',
    projectId: 'micropong-ddbc2',
    authDomain: 'micropong-ddbc2.firebaseapp.com',
    storageBucket: 'micropong-ddbc2.firebasestorage.app',
    measurementId: 'G-H6F4PPBWNZ',
  );
}
