final List<Map<String, dynamic>> jasa = [
  {
    "image": "images/contoh_gambar.jpg",
    "title": "Pemograman Web",
    "location": "Surabaya",
    "name": "Ahmad Reza",
    "Start From": "Start From",
    "price": "Rp. 100.000",
    "rating": "4.5",
  },
  {
    "image": "images/contoh_gambar.jpg",
    "title": "Pemograman Mobile",
    "location": "Surabaya",
    "name": "Frisqi Firmasnyah",
    "Start From": "Start From",
    "price": "Rp. 200.00",
    "rating": "4.5",
  },
  {
    "image": "images/contoh_gambar.jpg",
    "title": "Apa aja gw bisa",
    "location": "Surabaya",
    "name": "Yusran Yuris",
    "Start From": "Start From",
    "price": "Rp. 300.000",
    "rating": "4.5",
  },
  {
    "image": "images/contoh_gambar.jpg",
    "title": "Pijet",
    "location": "Surabaya",
    "name": "John Doe",
    "Start From": "Start From",
    "price": "Rp. 100.000",
    "rating": "4.5",
  },
  {
    "image": "images/contoh_gambar.jpg",
    "title": "Pijet",
    "location": "Surabaya",
    "name": "John Doe",
    "Start From": "Start From",
    "price": "Rp. 100.000",
    "rating": "4.5",
  },
];
